AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.1
  Exclude:
  - 'vendor/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%r': '{}'
